# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
cloned_from = "https://github.com/fastly/compute-starter-kit-typescript-default"
description = ""
language = "javascript"
manifest_version = 3
name = "compute"
service_id = ""

[local_server]
[local_server.backends]
[local_server.backends.esbuild-server]
url = "http://localhost:3000"
override_host = "localhost:3000"

[local_server.secret_stores]
[[local_server.secret_stores.api-keys]]
key = "esbuild-server"
env = "BUILD_API_KEY"

[local_server.kv_stores]
[[local_server.kv_stores.code-blocks]]
key = "dummy"
data = ""

[scripts]
build = "npm run build"
post_init = "npm install"
